apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: predictyourday
  namespace: predictyourday
spec:
  gateways:
    - predictyourday-gateway  # 👈 external gateway
  hosts:
    - "*"
  http:
    - route:
        - destination:
            host: predictyourday-primary
            port:
              number: 3000
          weight: 100
        - destination:
            host: predictyourday-canary
            port:
              number: 3000
          weight: 0
