apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: predictyourday
  namespace: predictyourday
spec:
  gateways:
    - predictyourday-gateway  # Change from "mesh" to this
  hosts:
    - "*"
  http:
    - route:
        - destination:
            host: predictyourday-primary
          weight: 100
        - destination:
            host: predictyourday-canary
          weight: 0
