apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: predictyourday
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/predictyourday         # ✅ This is relative to repo root
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
