apiVersion: v1
kind: Service
metadata:
  name: predictyourday
spec:
  selector:
    app: predictyourday
  ports:
    - name: http 
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
